<?php
 
// Firebase API Key
define('FIREBASE_API_KEY', 'AAAAynpIyRg:APA91bH9bKLdGzgzmIbjJuNI3x3WyoP6U-E5EOF1VGOHticrKC5pReY5ZGHS_msfU38TEffsMq1yzVThEm5jJWnIEA1oFjY6GVWeOyUpFksdpw2m-H85xNxMuozAxOEAOZE2ZjZ1-SAI');

?>